### ISSUE TITLE
User should see LINE rich menu

### ISSUE THREAD

**Issue by katopz** [catcatio/catcat-firebase#22]
- [x] Events : [Show event with `BOOK` or `CANCEL` button](https://github.com/catcatio/catcat-firebase/issues/23)
- [x] Tickets : Show booked ticket card
- [x] Share : https://github.com/catcatio/catcat-firebase/issues/18
- [x] Balance : https://github.com/catcatio/catcat-firebase/issues/8
- [x] Suggestions : https://github.com/catcatio/catcat-firebase/issues/20
- [x] Help : https://github.com/catcatio/catcat-firebase/issues/21

**Comment by NiponChi** [comment]
See Rich menu api https://developers.line.me/en/docs/messaging-api/using-rich-menus/#create-a-rich-menu
