### ISSUE TITLE
catcat-bots stops working when incoming message is undefined

### ISSUE THREAD

**Issue by niponchi** [catcatio/catcat-firebase#25]
catcat-bots    | 210 | 54.84MB | ✏️  	--> undefined
catcat-bots    | [dev]
catcat-bots    | /usr/app/node_modules/@google-cloud/translate/src/index.js:211
catcat-bots    | [dev]         callback(err, null, resp);
catcat-bots    | [dev]         ^
catcat-bots    | [dev]
catcat-bots    | [dev] TypeError: callback is not a function
catcat-bots    | [dev]     at /usr/app/node_modules/@google-cloud/translate/src/index.js:211:9
catcat-bots    | [dev]     at Object.handleResp (/usr/app/node_modules/@google-cloud/common/src/util.js:135:3)
catcat-bots    | [dev]     at /usr/app/node_modules/@google-cloud/common/src/util.js:465:12
catcat-bots    | [dev]     at Request.onResponse [as _callback] (/usr/app/node_modules/retry-request/index.js:198:7)
catcat-bots    | [dev]     at Request.self.callback (/usr/app/node_modules/request/request.js:185:22)
catcat-bots    | [dev]     at emitTwo (events.js:126:13)
catcat-bots    | [dev]     at Request.emit (events.js:214:7)
catcat-bots    | [dev]     at Request.<anonymous> (/usr/app/node_modules/request/request.js:1161:10)
catcat-bots    | [dev]     at emitOne (events.js:116:13)
catcat-bots    |     at Request.emit (events.js:211:7)
catcat-bots    | [dev]
catcat-bots    | app crashed
catcat-bots    | [dev]
catcat-bots    | npm run dev exited with code 0
catcat-bots    | -->
catcat-bots    | Sending SIGTERM to other processes..

**Comment by NiponChi** [comment]
PM2 didn't restart the process in this case. Need to restart manually

**Comment by NiponChi** [comment]
Fixed the undefinded error here. https://github.com/catcatio/catcat-bots/commit/0da3ff1e2179d86facb115472decd4557643e909

Still need to make PM2 to restart the process

**Comment by NiponChi** [comment]
Root cause found -> it was a sticker message
```
{"type":"message","replyToken":"c326ba6a42984d338b906271da26e270","source":{"userId":"U86f2fb79bb0a5fd53070ac495913a5ff","type":"user"},"timestamp":1535544992850,"message":{"type":"sticker","id":"8492769529779","stickerId":"52002740","packageId":"11537"}}
```

**Comment by niponchi** [comment]
Fixed in https://github.com/catcatio/catcat-bots/commit/0da3ff1e2179d86facb115472decd4557643e909
