### ISSUE TITLE
Empty profile image

### ISSUE THREAD

**Issue by niponchi** [catcatio/catcat-firebase#26]
catcat-firebase    | 174 | 35.64MB | ✏️  start get ticket params
catcat-firebase    | 174 | 35.64MB | ✏️  line_U9c02e5d0b4c519d31b0154ec57c4c555 line U9c02e5d0b4c519d31b0154ec57c4c555
catcat-firebase    | info: 174 | 35.89MB | ✏️  getTicketParams:get took  174 ms
catcat-firebase    | info: 174 | 35.89MB | ✏️  { text: 'https://ticket.catcat.io/v1/use/f7733c5e39e5d72aed7be72bc3ec2bfbfc4c44a29b7c0726757bb3917dc14a41',
catcat-firebase    |   logoUrl: 'empty',
catcat-firebase    |   logoText: 'GREAT',
catcat-firebase    |   maskTextLine1: 'BOT',
catcat-firebase    |   maskTextLine2: '101' }
catcat-firebase    | info: 174 | 35.89MB | ✏️  getTicketParams:all took  179 ms

**Comment by NiponChi** [comment]
In this case, sever did not return pictureUrl.
```
{
  "userId": "U9c02e5d0b4c519d31b0154ec57c4...",
  "displayName": "GREAT"
}
```

**Comment by niponchi** [comment]
This happened because user did not set his profile image.
