### ISSUE TITLE
[catcat-bots] Error: Request failed with status code 400

### ISSUE THREAD

**Issue by niponchi** [catcatio/catcat-firebase#27]
catcat-bots    | 184 | 53.86MB | ✏️  	--> ดูตั๋ว
catcat-bots    | [dev]
catcat-bots    | 184 | 52.65MB | ✏️  total language detection time (th):  185
catcat-bots    | [dev]
catcat-bots    | 184 | 52.51MB | 💥  Request failed with status code 400
catcat-bots    | [dev]
catcat-bots    | 184 | 51.77MB | 💥  Error: Request failed with status code 400
catcat-bots    | [dev]     at wrapError (/usr/app/node_modules/@line/bot-sdk/dist/http.js:10:15)
catcat-bots    | [dev]     at <anonymous>
catcat-bots    | [dev]     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by NiponChi** [comment]
This error showed after each incoming message

**Comment by NiponChi** [comment]
Root cause found, it is because some responses from fulfillment are in dialog format, and we directly forward it to line, so line service returns 400
