### ISSUE TITLE
User can't join event when `quick reply` not support

### ISSUE THREAD

**Issue by katopz** [catcatio/catcat-firebase#29]
![image](https://user-images.githubusercontent.com/97060/44829089-264b7380-ac45-11e8-98f9-7407f8cad2a8.png)
![image](https://user-images.githubusercontent.com/97060/44829096-2f3c4500-ac45-11e8-9722-85c836ecf50a.png)
![image](https://user-images.githubusercontent.com/97060/44829099-34998f80-ac45-11e8-9339-c0b0b0905c35.png)
![image](https://user-images.githubusercontent.com/97060/44829103-3b280700-ac45-11e8-9e43-e72e91f57795.png)
![image](https://user-images.githubusercontent.com/97060/44829108-411de800-ac45-11e8-93de-af4226ec0013.png)
![image](https://user-images.githubusercontent.com/97060/44829113-4844f600-ac45-11e8-9e88-1635cd19aaf4.png)

**Comment by katopz** [comment]
> Note: The quick reply feature is supported on LINE 8.11.0 and later for iOS and Android.

User use 8.2.2

![455036](https://user-images.githubusercontent.com/97060/44830806-c60cff80-ac4d-11e8-8b1f-ace17fc79f98.jpg)

Now we should focus on workaround, why it's not accept manual input? Maybe we use card instead?

**Comment by niponchi** [comment]
Should be fixed with #40
