### ISSUE TITLE
User should see `invite event` process after booked

### ISSUE THREAD

**Issue by katopz** [catcatio/catcat-firebase#33]
// After booked
Bot :  `Oh BTW, Do you want to invite your friend to this event?`
```
Sharing is caring ;)
____________________
[ invite ]
```
`[ invite ]` = line://msg/text/?https://t.catcat.io/?ref={LINE_ID_EVENT_ID}

**Comment by niponchi** [comment]
![image](https://user-images.githubusercontent.com/20331936/45256400-2fb0aa80-b3c0-11e8-8f44-1e95485ea414.png)
![image](https://user-images.githubusercontent.com/20331936/45256404-33dcc800-b3c0-11e8-8fd9-e9941db20d12.png)

**Comment by katopz** [comment]
เพื่อนว่างาน? 😄

**Comment by katopz** [comment]
####  Eng
🤖 : Want to invite someone? Click "invite" before tickets running out!
🤖 :
```
Chatbots & Blockchain
🎫available 8 tickets
_________
[invite]
```

#### Thai
🤖 : รีบชวนเพื่อนก่อนตั๋วหมด กด "ชวนเพื่อน" ได้เลยจ้า
🤖 :
```
Chatbots & Blockchain
🎫เหลือ 8 ใบ
_________
[ชวนเพื่อน]
```

**Comment by niponchi** [comment]
![image](https://user-images.githubusercontent.com/20331936/45266306-4b30b980-b483-11e8-9970-91243e659b07.png)
![image](https://user-images.githubusercontent.com/20331936/45266307-4e2baa00-b483-11e8-8e85-18843a9154a9.png)
