### ISSUE TITLE
User can see multilingual cats response 

### ISSUE THREAD

**Issue by katopz** [catcatio/catcat-firebase#43]
😄 : I love you
🤖 : Meow~
😄 : รักน้าาาา
🤖 : เมี๊ยว~
😄 : LOL
🤖 : Meow~
😄 : 
![image](https://user-images.githubusercontent.com/97060/45277591-fe84c700-b4f2-11e8-9fa0-e9242d378049.png)
🤖 : Meow~

**Comment by niponchi** [comment]
Handled sticker message in https://github.com/catcatio/catcat-bots/commit/b0cfb7f9f9207172ead590a44f86a97e24c14320

**Comment by niponchi** [comment]
![image](https://user-images.githubusercontent.com/20331936/45345820-abce0c80-b5d1-11e8-89fd-f20ae9e57d6d.png)
