### ISSUE TITLE
User should see account balance by input `balance`

### ISSUE THREAD

**Issue by katopz** [catcatio/catcat-firebase#44]
🤖 : balance,​ coin, token, wallet, pocket, money
😄 : 
```
Balance
------------
1,000 XLM
200 CAT
30 LINK
------------
[ Refresh ] [ Transfer ]
```

🤖 : ตัง, เป๋า, กระเป๋า, เงิน, เหรียญ
😄 : 
```
เหรียญ
------------
1,000 XLM
200 CAT
30 LINK
------------
[ ขอดูอีกรอบ ] [ ส่งให้เพื่อน ]
```

> Transfer will throw `Aww, we're working on this feature meow~` `ยังส่งไม่ได้จ้า รอก่อนน้าเมี๊ยว~`
Related : https://github.com/catcatio/catcat-firebase/issues/38

**Comment by katopz** [comment]
Please sort token by alphabet

**Comment by katopz** [comment]
```
Balance (GABC...XKAT)
------------------------
1,000 XLM (GABC...DXLM)
200 CAT (GABC...XCAT)
30 LINK (GABC...LINK)
------------------------
[ Refresh ] [ Transfer ]
```

**Comment by niponchi** [comment]
![image](https://user-images.githubusercontent.com/20331936/45342980-b684a380-b5c9-11e8-8887-a9a703e54838.png)
![image](https://user-images.githubusercontent.com/20331936/45342983-b97f9400-b5c9-11e8-96a7-8053722397af.png)

**Comment by katopz** [comment]
```
👛 Wallet (GABC...XKAT)
------------------------
200 CAT 🐈
30 LINK (GABC...LINK)
1,000 XLM 🚀
------------------------
[ Refresh ] [ Transfer ]
```

```
👛 กระเป๋า (GABC...XKAT)
------------------------
200 CAT 🐈
30 LINK (GABC...LINK)
1,000 XLM 🚀
------------------------
[ ขอดูอีกรอบ ] [ ส่งให้เพื่อน ]
```

**Comment by niponchi** [comment]
![image](https://user-images.githubusercontent.com/20331936/45343727-eaf95f00-b5cb-11e8-92cf-42c4c317bca2.png)
![image](https://user-images.githubusercontent.com/20331936/45343732-f056a980-b5cb-11e8-9de3-a90aac39cfb6.png)

**Comment by niponchi** [comment]
![image](https://user-images.githubusercontent.com/20331936/45345857-c56f5400-b5d1-11e8-8a84-6497f1709e70.png)
