### ISSUE TITLE
Producer can create event card on the fly from Facebook events link

### ISSUE THREAD

**Issue by katopz** [catcatio/catcat-firebase#5]
### Expected
Producer : 
```
https://m.facebook.com/events/205814763443058/
```
- - -
Bots : 
```
{{ picture }}
{{ title }}
{{ desc }}
{{ date }}
{{ venue }}
```
![image](https://user-images.githubusercontent.com/97060/44392647-e6a5cd00-a55c-11e8-9295-c88dd09c57ad.png)
```
Confirm create event?
```
`No` `Yes`
- - -

🤖 : How many seats?
😄 : 50
🤖 : How much for each tickets? (0=free)
😄 : 0
🤖 : Is this correct?
// Show sample of ticket here

**Comment by NiponChi** [comment]
- [ ] Add event title to dialogflow entities

**Comment by niponchi** [comment]
Event scraper service created: see [catcatio/fb-event-scraper](https://github.com/catcatio/fb-event-scraper)
