### ISSUE TITLE
Consumer should see an quick reply for start reading after purchased book

### ISSUE THREAD

**Issue by katopz** [catcatio/catcat-firebase#60]
🤖 : Thanks for purchase! Enjoy! Do you want to read it now
[Not yet] [Sure!]

🤖 : ขอบคุณที่สนับสนุนผู้เขียน ขอให้สนุกกับการอ่านนะ, อยากอ่านเลยรึเปล่า?
[ยังก่อน] [อ่านเลย]

**Comment by niponchi** [comment]
Quick reply added
