### ISSUE TITLE
Learning IPFS capabilities 🚀

### ISSUE THREAD

**Issue by katopz** [catcatio/catcat-firebase#68]
- [x] https://medium.com/@mycoralhealth/learn-to-securely-share-files-on-the-blockchain-with-ipfs-219ee47df54c
- [x] https://blog.cloudflare.com/e2e-integrity/
- [x] http://abcxyz.de/2018/02/08/using-ipfs-as-memo-in-stellar-transaction/

**Comment by katopz** [comment]
![image](https://user-images.githubusercontent.com/97060/46720848-d0360b00-cc9b-11e8-9df7-1f683df236b4.png)

**Comment by niponchi** [comment]
catcat-cloud: https://github.com/catcatio/catcat-cloud

**Comment by niponchi** [comment]
https://blog.cloudflare.com/building-with-workers-kv/

Up to 1 billion keys per namespace
Keys of up to 2 kB
Values of up to 64 kB
Eventually consistent, global consistency within 10 seconds
100k+ reads per second per key
Up to one write per second per key

>We worked hard to make the pricing of Workers KV easy to understand and affordable for virtually any use case. Your $5 monthly Workers compute minimum includes 1 GB of KV storage and up to 10 million KV reads. If you use less than the 10 million included Worker requests now, you can use KV without paying a single cent more.

>Beyond the minimums, Workers KV is billed at $0.50 per GB-month of additional storage and $0.50 per million additional KV reads.
