### ISSUE TITLE
User should see account balance by input any Stellar public key

### ISSUE THREAD

**Issue by katopz** [catcatio/catcat-firebase#8]
User : `GAVDMUW57KMPYK7EL4CA6INS2ERHQJDRI33TIKYDDCLHWDGC6WNQJBLQ`
Bot : 
```
100 XLM
200 CAT
```

**Comment by NiponChi** [comment]
committed in https://github.com/catcatio/catcat-firebase/commit/5d8b154c56300f842fdf4e1f81326b96fa359ad8
